package org.siouan.frontendgradleplugin.domain.exception;

public enum IOErrorCode {
    CHANNEL_CLOSE_ERROR,
    DATA_TRANSFER_ERROR,
    EXECUTABLE_NOT_FOUND_ERROR,
    FILE_MOVE_ERROR,
    NON_WRITABLE_FILE_ERROR,
    NON_DOWNLOADABLE_RESOURCE_ERROR,
    SLIP_ATTACK_ERROR,
    UNSUPPORTED_ARCHIVE_ENTRY_ERROR
}
