matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk8
      git:
        depth: false
      addons:
        sonarcloud:
          organization: siouan
          token:
            secure: "I7ymzi1DWGQ3JZqmWRYyCb5UuNRhH0ieSSZlspzPsnoYxFJNhxYhkL2CaijPbhR06Acnvjn0txKeJrvTNxG4dq4efe5jCMHqzIjLJ7AGRVppBC1t4DszoZ0ovrXldsZ4MjILEwFZdUrPiAynUYgQR0z/cN5LBD0wn+dwjbmp2GvJWg/r1IlodShI2f5eFO3hy8g/4361xGkv3ROVvGbL7YmaSNJ80sJEcAGBKi1NDi91bZ3azUoQ2e7QVLTvWhfpB6HBm0lHH4oe2Ie/tJAFBiuf94QDS0C38pGI8YqnIig5uvoerZLxc96EoxyJ555OT8dcxYf1thSaW1Mo2HerOvmtQtt7+58l0SDX51VCwv0t7+Whh84DLKiU28PntGV8YXjfyuTsbxiCTpyh0CJzOocVH/XaMU5MO58spITo4X9xK9NYzvbKmKVvGYiQw0CUsJ5XYkhjqrGq5aZJSVrUFX72vvV31zw/KCwnqxO5lkZc+SOoynIHfn/s8l1dG40rLEs5/zXG4GXMsBe3T2S7ieZGy2TaJMQyiyg/0Yx8VvmV/ex0oxKRpe4a+/CyhhxDjDSDukSTdVY+gCq97ZVdafNi7ltIqndTUErOwt8BRsOMUFWzuwNq6UZuDjAQ4gHhKVO0827AH7/pD8hMBlBGsT1hp4njT/fwUPET0OoWz5M="
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.sonar/cache
      script:
        - ./gradlew check jacocoTestReport --scan
        - sonar-scanner

    - os: linux
      dist: bionic
      jdk: openjdk11

    - os: osx
      osx_image: xcode9.4
      jdk: oraclejdk11

    - os: windows
      # Java is not yet supported on Windows, so the build would block.
      # You do not need any setup from Travis, use a plain bash build
      language: bash
      env:
        # This is a convenience variable for shortening download commands
        - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
        # If you use Windows, you may want to disable Windows Defender. It slows down the builds
        # dramatically, also during cache setup. From a Tanzinul Islam's idea: http://bit.ly/348VPYS,
        # This work around disables it before caching
        - NO_WIN_DEFENDER=$(curl "${GRAVIS}.disable-windows-defender.sh" --output .no-defender.sh && source .no-defender.sh)
        # List any JDK you want to build your software with.
        # You can see the list of supported environments by installing Jabba and using ls-remote:
        # https://github.com/shyiko/jabba#usage
        - JDK="adopt-openj9@1.8"
      before_install:
        # Download the script, and download, install, configue the JDK, and export the configuration to the current shell
        - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
        - source ~/.install-jdk-travis.sh
      before_cache:
        - curl "${GRAVIS}.clean_gradle_cache.sh" --output ~/.clean_gradle_cache.sh
        - bash ~/.clean_gradle_cache.sh

language: java

git:
  depth: 3

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew check --scan
