[versions]
assertj-version = "3.27.7"
commons-compress-version = "1.28.0"
gradle-plugin-publish-version = "2.2.1"
httpclient5-version = "5.6.4"
jacoco-version = "0.8.15"
json-version = "20260814"
junit-jupiter-version = "6.1.3"
junit-pioneer-version = "2.3.0"
lombok-version = "1.18.48"
mockito-version = "5.23.0"
resilience4j-retry-version = "2.4.0"
sonarqube-version = "7.5.0.8588"
wiremock-version = "3.13.2"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-version" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress-version" }
httpclient5 = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "httpclient5-version" }
json = { module = "org.json:json", version.ref = "json-version" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter-version" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-version" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter-version" }
junit-pioneer = { module = "org.junit-pioneer:junit-pioneer", version.ref = "junit-pioneer-version" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok-version" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-version" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito-version" }
resilience4j-retry = { module = "io.github.resilience4j:resilience4j-retry", version.ref = "resilience4j-retry-version" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock-version" }

[plugins]
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish-version" }
sonarqube = { id  ="org.sonarqube", version.ref = "sonarqube-version" }
