name: Publish website

on:
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]

    steps:
      - name: Init Ubuntu environment
        if: matrix.os == 'ubuntu-24.04'
        run: sudo rm -f /usr/local/bin/node /usr/local/bin/npm /usr/local/bin/pnpm /usr/local/bin/yarn

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          architecture: x64

      - name: Cache Gradle's cache and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant executable permission
        run: chmod +x gradlew

      - name: Build website
        run: |
          ./gradlew :site:assembleFrontend --console=plain

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/dist

      - name: Stop Gradle before caching
        run: ./gradlew -stop

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
